included:
  - apps/macos/BaxterApp
  - apps/macos/BaxterAppTests

excluded:
  - apps/macos/BaxterApp.xcodeproj

reporter: "github-actions-logging"

only_rules:
  - force_cast
  - force_try
  - unused_import
  - empty_count
  - trailing_whitespace

trailing_whitespace:
  ignores_empty_lines: true
